language: java
jdk: oraclejdk8

dist: xenial

addons:
  firefox: "54.0.1"

# disable default mvn install
install: true

notifications:
  slack: qaengineering:eTRqy0JhQOUtKHNO8mKLc8NC

env:
  global:
    # set PATH to include desired firefox as the firefox-addon doesn't seem to work properly
    #- PATH="/tmp/firefox:$PATH"
    - CAPTURE_URL="https://capture.unity.perimeterusa.com:5000"
    - SUT_NAME="frameworkium-bdd"
    - SUT_VERSION=${TRAVIS_BRANCH}
    - THREAD_COUNT=2
    - SELENIUM_MAJ_VER=3.4
    - SELENIUM_VER=${SELENIUM_MAJ_VER}.0
    - SELENIUM_JAR=selenium-server-standalone-${SELENIUM_VER}.jar
    - GECKO_VER=0.18.0

before_script:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

script:
  # install
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -q

  # Download and setup Grid
  - wget --quiet --no-check-certificate https://selenium-release.storage.googleapis.com/${SELENIUM_MAJ_VER}/${SELENIUM_JAR}
  - java -Xmx128m -jar ${SELENIUM_JAR} -role hub > /dev/null 2>&1 &

  # Extract Firefox as the firefox-addon doesn't seem to work
  #- tar -xjf /tmp/firefox*.tar.bz2 --directory /tmp

  # Download and setup Marionette/geckodriver grid node
  - wget --quiet --no-check-certificate https://github.com/mozilla/geckodriver/releases/download/v${GECKO_VER}/geckodriver-v${GECKO_VER}-linux64.tar.gz
  - tar -xzf geckodriver-v${GECKO_VER}-linux64.tar.gz --directory /tmp
  - java -Xmx128m -Dwebdriver.gecko.driver=/tmp/geckodriver -jar ${SELENIUM_JAR} -role node -hub http://localhost:4444/grid/register -browser browserName=firefox,maxInstances=${THREAD_COUNT} -maxSession ${THREAD_COUNT} -port 5555 > /dev/null 2>&1 &

  # Run on Firefox off the grid
  - mvn verify -B -Dthreads=$THREAD_COUNT -Dbrowser=firefox -Dwebdriver.gecko.driver=/tmp/geckodriver 2> /dev/null

  # Run on Firefox on the grid
  - mvn verify -B -Dthreads=$THREAD_COUNT -Dconfig=FirefoxGrid.yaml -DcaptureURL=$CAPTURE_URL -DsutName="$SUT_NAME" -DsutVersion="$SUT_VERSION"

  # Run single test with tags parameter
  - mvn verify -B -Dtags="@CustomTag" -Dthreads=$THREAD_COUNT -Dbrowser=firefox -Dwebdriver.gecko.driver=/tmp/geckodriver 2> /dev/null

  # generate allure report
  - mvn site -B -q
